---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Data_view1/Data_view1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/174980/articles/211790/master/file/figures/Data_view1/Data_view1.png"
    folder_url: "/users/174980/articles/211790/master/folder/figures/Data_view1"
