---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/plot1/plot1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/174980/articles/210362/master/file/figures/plot1/plot1.png"
    folder_url: "/users/174980/articles/210362/master/folder/figures/plot1"
