---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/show_location_output/show_location_output.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/174980/articles/210362/master/file/figures/show_location_output/show_location_output.png"
