---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/moods_median/moods_median.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/174980/articles/211790/master/file/figures/moods_median/moods_median.png"
